### PR TITLE
AutoWalk

### PR DESCRIPTION
**Pull request by christallinqq**

### CODE REVIEW

**Comment by HausemasterIssue** [comment]
wtf is the proxy for?

**Comment by christallinqq** [comment]
> 
> 
> wtf is the proxy for?

that wasn't supposed to be a part of it lol

**Comment by HausemasterIssue** [comment]
good lol, and what about the wrapper? i dont see a use for that

**Comment by christallinqq** [comment]
that was just stuff i was experimenting with, the wrapper can be useful in the future

**Comment by HausemasterIssue** [comment]
if it's not useful now, leave it out, i want to remove as much bloat as possible

**Comment by christallinqq** [comment]
alright

**Pull request closed without merging**
