### PR TITLE
xray

### PR DESCRIPTION
**Pull request by xgraza**
ref: https://github.com/HausemasterIssue/spidersense/issues/30

### CODE REVIEW

**Comment by HausemasterIssue** [comment]
based, but i need your help.

i need surround to do nothing and just pause if ur surrounded with obi or bedrock, then reactivate if ur not, then pause again

**Comment by HausemasterIssue** [comment]
could i include those in the pr too?

**Comment by HausemasterIssue** [comment]
ight

**Comment by Sxmurai** [comment]
ill do the surround thing in a separate pr

**Pull request merged**
