### PR TITLE
best module real

### PR DESCRIPTION
**Pull request by christallinqq**

### CODE REVIEW

**Review by HausemasterIssue — DISMISSED** [review]
dont change build.gradle please

**Comment by HausemasterIssue** [comment]
hmmm

**Comment by HausemasterIssue** [comment]
coord leaker kinda useless lol

**Comment by HausemasterIssue** [comment]
ok

**Comment by christallinqq** [comment]
> 
> 
> dont change build.gradle please

i had to or else i would get java.lang.NullPointerException

**Comment by HausemasterIssue** [comment]
ight, i fixed noslow btw

**Pull request merged**
