### PR TITLE
Rename "Aura" to "Killaura", & added NoPush.

### PR DESCRIPTION
**Pull request by christallinqq**

### CODE REVIEW

**Comment by HausemasterIssue** [comment]
nopush is already a thing its in velocity lol

**Comment by HausemasterIssue** [comment]
also aura is a better name for kill aura. but, i do need some help with something. you need to figure out a way for the surround module to pause when you are surrounded with obi, then turn on agian to replace obi, then pause etc. could u do that pls?

**Comment by christallinqq** [comment]
oh shit i didn't realize

**Comment by HausemasterIssue** [comment]
yeah, could u help with surround tho?

**Comment by christallinqq** [comment]
> 
> 
> also aura is a better name for kill aura. but, i do need some help with something. you need to figure out a way for the surround module to pause when you are surrounded with obi, then turn on agian to replace obi, then pause etc. could u do that pls?

wym

**Comment by HausemasterIssue** [comment]
like, i want the surround do be able to detect if you are surrounded by obi, and if you aren't then it should surround u, but if you are surrounded by obi then the module should do nothing, and basically just pause, but reenable when you are not surrounded by obi

yk what i mean?

**Comment by christallinqq** [comment]
> 
> 
> like, i want the surround do be able to detect if you are surrounded by obi, and if you aren't then it should surround u, but if you are surrounded by obi then the module should do nothing, and basically just pause, but reenable when you are not surrounded by obi
> 
> yk what i mean?

so you want it to always be enabled but pause when ur surrounded?

**Comment by HausemasterIssue** [comment]
yes, i want it to be enabled but pause when you are surrounded. and completely disable if the user disables it themselves or you are off ground.

**Comment by HausemasterIssue** [comment]
get it?

**Comment by christallinqq** [comment]
yeah

**Comment by HausemasterIssue** [comment]
ight, the automine is a good idea, but you could build on it and make autotunnel, autotunnel would be more useful.

**Comment by christallinqq** [comment]
alright

**Comment by HausemasterIssue** [comment]
yeah, make a pr with the surround fix and the autotunnel when ur ready :)

**Pull request closed without merging**
