### PR TITLE
added sum words and fix the ,

### PR DESCRIPTION
**Pull request by master7720**

### CODE REVIEW

**Comment by master7720** [comment]
bruh lmao you just fix it ok nvm

**Comment by HausemasterIssue** [comment]
only words allowed in the toxic category is the kinda shit u see spammed on cc lol, thats what i was going for lol

**Comment by master7720** [comment]
dude the things i said are fucking terrifying

**Comment by master7720** [comment]
how would you like it if your pillows were hot on both sides

**Comment by master7720** [comment]
and getting food stuck up your teeth thats just.....huuuu

**Comment by HausemasterIssue** [comment]
@master7720 throw away the pillow, get a toothpick, ez fix

**Pull request closed without merging**
