### PR TITLE
AutoClicker

### PR DESCRIPTION
**Pull request by christallinqq**
module

### CODE REVIEW

**Comment by HausemasterIssue** [comment]
ok, i will add the credits and stuff, but what i really need is the surround to work better pls

**Comment by HausemasterIssue** [comment]
also i need help with fastswim, it says at line 113 there is a nulll pointer exception, i don't see why, could u take a look at it pls? sorry if im annoying, we will get to da fun stuff soon.

**Comment by christallinqq** [comment]
can u accept this so i can commit another pr

**Comment by HausemasterIssue** [comment]
k

**Pull request merged**
